---
- name: create user
  hosts: all
  tasks:
   - name: user creation
     user:
      name: Hari
      password: intelliqit
      uid: 1890
      home: /home/ubuntu/Hari
      comment: "A normal user"
      shell: /bin/bash

