---
- name: implemeting tag
  hosts: all
  tasks:
    - name: install tree
      apt:
       name: tree
       state: present
       update_cache: yes
      tags: tree_installtion
    - name: create user
      user:
       name: usha
       password: intelliqit
      tags: create install
    - name: copy file
      copy: 
       src: /etc/password
       dest: /tmp
      
