---
- name: implementing handller
  hosts: all
  tasks:
   - name: install apache2
     apt:
      name: apache2
      state: present
      update_cache: yes
   - name: edit index.html file
     copy:
      content: "well come to my home"
      dest: /var/www/html/index.html
      notify: restart apache2
  handlers:
   - name: restart apache2
     service: 
      name: apache2
      state: restarted
      

