---
- name: install jenkins
  hosts: all
  tasks:
    - name: jenkins install
      apt: 
       name: "{{item.a}}"
       state: present
       update_cache: "{{item.b}}"
      with_items: 
       - {a: openjdk-8-jdk,b: present,c: yes}
       - {a: maven,b: present,c: no}
       - {a: git,b: present,c: no}
    - name: download jenkins.war
      get_url:
       url: https://get.jenkins.io/war-stable/2.332.3/jenkins.war
       dest: /home/ubuntu 
    - name: install tomcat9
      hosts: all
      tasks:
      